---
- name: Install Httpd and enable intranet
  hosts: test-server
  become: true
  gather_facts: true
  tasks:
    - name: yum update
      yum: name=* state=latest
    - name: Install Apache2
      yum:
        name:
        - httpd
        - firewalld
        state: latest
    - name: Copy content to index.html
      copy:
        content: "Welcome to my page - Zidan!!!"
        dest: /var/www/html/index.html
    - name: Enable and start Firewall
      service:
        name: firewalld
        enabled: true
        state: started
          # - name: Permit access to httpd
          #firewalld:
          #service: http
          # permanent: true
          #state: enabled
          #immediate: yes
    - name: Enable and start httpd
      service:
        name: httpd
        enabled: true
        state: started
...