---
- hosts: test-server
  become: true
  tasks:
    - name: install nginx
      package: pkg=nginx state=installed

      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started